/**
 * Builds card-safe 3:2 artwork without altering the collectible itself.
 *
 * Older object renders are square. Showing them with `contain` in a 3:2 card
 * exposes empty bars. This build step creates one crisp, full-frame 3:2 image
 * with attention-aware framing, matching the finished character artwork. It
 * never duplicates, blurs or tints the source into side panels.
 *
 * Original PNGs remain the source for depth maps and 3D relief materials.
 *
 *   npm run bake:display-art
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import sharp from 'sharp';

const REGISTRY_PATH = 'src/config/artRegistry.ts';
const OUTPUT_DIR = 'assets/collectee/display';
const WIDE_SOURCE_DIR = 'assets/collectee/display-sources/wide';
const COMPACT_OUTPUT_DIR = 'assets/collectee/display/compact';
const SQUARE_OUTPUT_DIR = 'assets/collectee/display/square';
const SQUARE_COMPACT_OUTPUT_DIR = 'assets/collectee/display/square/compact';
const OUTPUT_REGISTRY = 'src/config/displayArtRegistry.ts';
const WIDE_WIDTH = 1200;
const WIDE_HEIGHT = 800;
const COMPACT_WIDTH = 600;
const COMPACT_HEIGHT = 400;
const SQUARE_WIDTH = 800;
const SQUARE_COMPACT_WIDTH = 400;

interface SourceEntry {
  id: string;
  source: string;
}

function readRegistry(): SourceEntry[] {
  const registry = readFileSync(REGISTRY_PATH, 'utf8');
  const pattern = /^\s*'([^']+)':\s*(?:portrait|object|scene)\(\s*require\('([^']+)'\)/gm;
  const entries: SourceEntry[] = [];
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(registry)) !== null) {
    entries.push({ id: match[1]!, source: match[2]! });
  }

  if (entries.length === 0) throw new Error('No item artwork found in artRegistry.ts');
  return entries;
}

async function buildDisplayAsset(entry: SourceEntry): Promise<void> {
  const sourcePath = resolve(dirname(REGISTRY_PATH), entry.source);
  const wideSourceOverride = resolve(WIDE_SOURCE_DIR, `${entry.id}.png`);
  const wideSourcePath = existsSync(wideSourceOverride) ? wideSourceOverride : sourcePath;
  const outputPath = resolve(OUTPUT_DIR, `${entry.id}.jpg`);

  /* Verified weapons with long silhouettes have hand-approved 3:2 masters.
     Keeping those outside the generated directory prevents a rebuild from
     replacing their safe framing with a square-to-landscape crop. */
  await sharp(wideSourcePath)
    .resize(WIDE_WIDTH, WIDE_HEIGHT, {
      fit: 'cover',
      position: sharp.strategy.attention,
      kernel: sharp.kernel.lanczos3,
    })
    .jpeg({ quality: 95, chromaSubsampling: '4:4:4' })
    .toFile(outputPath);

  // 600 physical pixels covers a two-column phone card at 3x density without
  // asking mobile devices to decode the full desktop texture for every tile.
  await sharp(outputPath)
    .resize(COMPACT_WIDTH, COMPACT_HEIGHT, { fit: 'fill', kernel: sharp.kernel.lanczos3 })
    .jpeg({ quality: 92, chromaSubsampling: '4:4:4' })
    .toFile(resolve(COMPACT_OUTPUT_DIR, `${entry.id}.jpg`));

  /* Square boxes are common in news, collection mosaics and compact pickers.
     Baking them from the original avoids cropping the ends of a gun or blade
     from the already-landscape card rendition. */
  const squareOutputPath = resolve(SQUARE_OUTPUT_DIR, `${entry.id}.jpg`);
  await sharp(sourcePath)
    .resize(SQUARE_WIDTH, SQUARE_WIDTH, {
      fit: 'cover',
      position: sharp.strategy.attention,
      kernel: sharp.kernel.lanczos3,
    })
    .jpeg({ quality: 95, chromaSubsampling: '4:4:4' })
    .toFile(squareOutputPath);

  await sharp(squareOutputPath)
    .resize(SQUARE_COMPACT_WIDTH, SQUARE_COMPACT_WIDTH, {
      fit: 'fill',
      kernel: sharp.kernel.lanczos3,
    })
    .jpeg({ quality: 92, chromaSubsampling: '4:4:4' })
    .toFile(resolve(SQUARE_COMPACT_OUTPUT_DIR, `${entry.id}.jpg`));
}

function writeRegistry(entries: SourceEntry[]): void {
  const lines = entries.map(
    ({ id }) =>
      `  '${id}': {\n` +
      `    wide: require('../../assets/collectee/display/${id}.jpg'),\n` +
      `    compact: require('../../assets/collectee/display/compact/${id}.jpg'),\n` +
      `    squareWide: require('../../assets/collectee/display/square/${id}.jpg'),\n` +
      `    squareCompact: require('../../assets/collectee/display/square/compact/${id}.jpg'),\n` +
      `  },`,
  );
  const source = `/**\n * Generated by scripts/bake-display-art.ts. Do not hand-edit.\n * Card-safe artwork only; 3D surfaces continue to use artRegistry's originals.\n */\n\nimport type { ImageSourcePropType } from 'react-native';\n\nexport interface DisplayArtSource {\n  wide: ImageSourcePropType;\n  compact: ImageSourcePropType;\n  squareWide: ImageSourcePropType;\n  squareCompact: ImageSourcePropType;\n}\n\nexport const DISPLAY_ART: Record<string, DisplayArtSource> = {\n${lines.join('\n')}\n};\n`;
  writeFileSync(OUTPUT_REGISTRY, source);
}

async function main(): Promise<void> {
  const entries = readRegistry();
  mkdirSync(OUTPUT_DIR, { recursive: true });
  mkdirSync(COMPACT_OUTPUT_DIR, { recursive: true });
  mkdirSync(SQUARE_OUTPUT_DIR, { recursive: true });
  mkdirSync(SQUARE_COMPACT_OUTPUT_DIR, { recursive: true });

  for (const entry of entries) {
    await buildDisplayAsset(entry);
    console.log(`Built ${entry.id}`);
  }

  writeRegistry(entries);
  console.log(`Wrote ${entries.length} display assets and ${OUTPUT_REGISTRY}`);
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
