/**
 * Extracts each item's dominant colour from its render — a build step.
 *
 * `domain/roomSuggestion.ts` scores room themes partly on whether their palette
 * matches what a collection actually looks like. That needs a colour per item,
 * and the only honest source is the artwork itself.
 *
 * Runs offline and writes a TypeScript map, so the app ships numbers rather
 * than doing image work at runtime (§12.1 — no network, no heavy lifting during
 * the demo).
 *
 *   npm run bake:palette
 */

import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

import sharp from 'sharp';

const SOURCE_DIRS = ['assets/collectee/items', 'assets/collectee/subjects'];
const OUT = 'src/config/itemPalette.ts';

/**
 * Renders sit on near-black. Averaging naively returns "dark grey" for every
 * item, which tells the recommender nothing — so background pixels are dropped
 * and only the subject contributes.
 */
const BACKGROUND_CUTOFF = 30;

/**
 * Weight by saturation as well as presence. A skin reads by its accent — the
 * dragon's orange, the karambit's gold — not by the large neutral mass of
 * gunmetal that would otherwise dominate a flat average.
 */
function dominantColour(pixels: Buffer, channels: number): [number, number, number] {
  let r = 0;
  let g = 0;
  let b = 0;
  let weight = 0;

  for (let i = 0; i < pixels.length; i += channels) {
    const pr = pixels[i]!;
    const pg = pixels[i + 1]!;
    const pb = pixels[i + 2]!;
    const max = Math.max(pr, pg, pb);
    const min = Math.min(pr, pg, pb);
    if (max < BACKGROUND_CUTOFF) continue;

    const saturation = max === 0 ? 0 : (max - min) / max;
    const w = 0.25 + saturation * 1.75;
    r += pr * w;
    g += pg * w;
    b += pb * w;
    weight += w;
  }

  if (weight === 0) return [128, 128, 128];
  return [Math.round(r / weight), Math.round(g / weight), Math.round(b / weight)];
}

async function main() {
  const sourceCandidates = SOURCE_DIRS.flatMap((dir) =>
    existsSync(dir)
      ? readdirSync(dir)
          .filter((f) => f.endsWith('.png'))
          .map((f) => join(dir, f))
      : [],
  );

  // Keep original renders beside upgraded variants, but publish one colour per
  // catalogue id. A `-vN` asset wins over the unversioned source, and the
  // highest version wins when several iterations exist.
  const sources = new Map<string, { path: string; version: number }>();
  for (const src of sourceCandidates) {
    const fileId = basename(src, '.png');
    const match = fileId.match(/^(.*)-v(\d+)$/);
    const id = match?.[1] ?? fileId;
    const version = match ? Number(match[2]) : 0;
    const current = sources.get(id);
    if (!current || version > current.version) sources.set(id, { path: src, version });
  }

  const entries: string[] = [];
  for (const [id, source] of [...sources.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    // 64px is plenty for an average and keeps 93 images fast.
    const { data, info } = await sharp(source.path)
      .flatten({ background: '#000000' })
      .resize(64, 64, { fit: 'fill' })
      .raw()
      .toBuffer({ resolveWithObject: true });

    const [r, g, b] = dominantColour(data, info.channels);
    entries.push(`  '${id}': [${r}, ${g}, ${b}],`);
  }

  writeFileSync(
    OUT,
    `/**
 * Dominant colour per item, as [r, g, b].
 *
 * Generated by \`npm run bake:palette\` from the renders themselves — background
 * pixels dropped, remaining pixels weighted by saturation so an item reads by
 * its accent rather than by its neutral mass.
 *
 * Feeds the palette signal in \`domain/roomSuggestion.ts\`. Regenerate rather
 * than hand-editing.
 */

export const ITEM_COLOUR: Record<string, readonly [number, number, number]> = {
${entries.join('\n')}
};

/** An item's dominant colour, or null when it has no render. */
export function colourFor(itemId: string): readonly [number, number, number] | null {
  return ITEM_COLOUR[itemId] ?? null;
}
`,
  );
  console.log(`Wrote ${entries.length} item colours to ${OUT}`);
}

main().catch((error) => {
  console.error('Palette bake failed:', error instanceof Error ? error.message : error);
  process.exit(1);
});
